// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFKabVyV6qnZe3zDUoRFWKDPShpEax514',
    appId: '1:931438847577:web:e9a9b5e5e9f59f8417b348',
    messagingSenderId: '931438847577',
    projectId: 'fanpageapp-b1fa6',
    authDomain: 'fanpageapp-b1fa6.firebaseapp.com',
    storageBucket: 'fanpageapp-b1fa6.appspot.com',
    measurementId: 'G-L612TXKGK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3GWkt9PgQtkAKuKl-lgDZnxEy1Pvzhx0',
    appId: '1:931438847577:android:fa79e1727b27d06417b348',
    messagingSenderId: '931438847577',
    projectId: 'fanpageapp-b1fa6',
    storageBucket: 'fanpageapp-b1fa6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmjAaCLYllQAYtBV_2Gy75veRJayeOWio',
    appId: '1:931438847577:ios:e06c849a1372f50617b348',
    messagingSenderId: '931438847577',
    projectId: 'fanpageapp-b1fa6',
    storageBucket: 'fanpageapp-b1fa6.appspot.com',
    iosClientId: '931438847577-h81kkl26ich75roc084s585aq6ln985t.apps.googleusercontent.com',
    iosBundleId: 'com.JamesLeonard.fanpageapp',
  );
}
